### ISSUE TITLE
PyPI Workflow contains unencrpyted secret key

### ISSUE THREAD

**Issue by No767** [chisaku-dev/pystatistics#3]
while going over the lib, I noticed that within the workflow, there seems to be a unencrypted secret. This means that there is a possible security risk. 

The way to normally solve this is going into the settings of this repo, and adding in a secret to the repo. and then add it to the workflow with the secret. 

should look something like this: `${{ secrets.[insert secret key name here] }}`

This is just a minor thing i noticed

**Comment by Isaac-To** [comment]
I didn't know exactly how to use this flow, so I just pasted the API token right on top, it has been revoked now. Thanks!
